---
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test_python39:
  image: python:3.9
  script:
    - pip install ".[dev]"
    - flake8
    - pylint rofi_pet_snippets/
    - mypy rofi_pet_snippets/
    - tox -e py39

test_python310:
  image: python:3.10
  script:
    - pip install ".[dev]"
    - tox -e py310
